# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  - master
  - dev

pool:
  vmImage: 'ubuntu-latest'


variables:
  buildConfiguration: 'Testing'
  Environment: 'Testing'
  OffLogs__TestApiToken: $(APITOKEN)
  
steps: 
  - task: UseDotNet@2
    displayName: DotNet Initialization
    inputs:
      packageType: 'sdk'
      version: '5.0.x'
  
  - script: |
      echo "{}" > Offlogs.Client.Tests/appsettings.Local.json
    displayName: 'Create empty config file'

  - task: DotNetCoreCLI@2
    displayName: Unit Tests
    inputs:
      command: test
      projects: '**Offlogs.Client.Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --logger trx --results-directory /opt/vsts/work/_temp/'

  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: "/opt/vsts/work/_temp/*.trx"
      mergeTestResults: true
      failTaskOnFailedTests: true